### ISSUE TITLE
Error from python.py Gst.Pipeline

### ISSUE THREAD

**Issue by nyboer** [hadware/gstreamer-python-player#1]
I tried running `python player.py` in python 2.7.9 with GStreamer Core Library version 1.4.4
I got the error:
`File "player.py", line 14, in __init__
    self.pipeline = Gst.Pipeline("mypipeline")
TypeError: GObject.__init__() takes exactly 0 arguments (1 given)`
I fixed it by changing line 14 to:
`self.pipeline = Gst.Pipeline.new("mypipeline")`

**Comment by hadware** [comment]
Alright, i'll change it, thanks!

**Comment by jamesaxl** [comment]
this project still alive ?

**Comment by hadware** [comment]
@jamesaxl well this isn't really a "project", more of a repo for me to put some code examples for something that took me some time to find.

But, yeah, i'm still alive.

**Comment by jamesaxl** [comment]
that is nice, if you do not mind I would like to add volume

**Comment by hadware** [comment]
Yeah go ahead, maybe create another example containing a simple play/pause player with a volume slider?

**Comment by jamesaxl** [comment]
ok no problem, Done. I will PR later

**Comment by hadware** [comment]
Alright, great. If you have more examples linked to GST's python API, go ahead and PR them
